# **07. Inici a la ciència de dades: Llibreria `NumPy`**

## Solucions dels exercicis 


In [1]:
import numpy as np

## **Exercici 1**

Emprant els _atributs_ dels _ndarray_ esbrineu en la següent cel·la:

In [2]:
mat_llista = [[1, 2, 3, 4] , [5, 6, 7, 8], [9, 10, 11, 12] ]
mat = np.array(mat_llista)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- les dimensions de la variable `mat` (_R:_ 2)

In [3]:
mat.ndim

2

- la seva forma, nombre de files i columnes (_R:_ (3,4))

In [4]:
mat.shape

(3, 4)

- el nombre d'elements que conté (_R:_ 12)

In [5]:
mat.size

12

- comproveu que l'element de la tercera fila, segona columna de la llista i la matriu NumPy són el mateix. Comproveu-ho en les dues variables. (_R:_ 10)

In [6]:
print(mat_llista[2][1])
mat_llista[2][1] == mat[2,1]

10


True

- creeu la mateixa matriu utilizant les funcions `arange` i `reshape`

In [7]:
mat2 = np.arange(1,13).reshape(3,4)
mat2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## **Exercici 2**

Crear el següent array de 3x3 i llavors:

```python
a = np.array( [[ 1,2,3], [4,5,6], [7,8,9]] )
```

In [8]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


    1) selecciona el número 6

In [9]:
a[1,2]

6

    2) selecciona els números 4, 5, 7 i 8. 

In [10]:
a[1:, :2]

array([[4, 5],
       [7, 8]])

    3) selecciona l'última fila

In [11]:
a[-1]

array([7, 8, 9])

    4) selecciona la primera fila

In [12]:
a[0]

array([1, 2, 3])

    5) inverteix l'ordre de les files de l'array

In [13]:
a[::-1, :]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

 6) selecciona els números: 2, 6, 7.

In [14]:
a[[0,1,2],[1,2,0]]

array([2, 6, 7])

## **Exercici 3**

Crea un vector nul (0s) de mida 10, però en que el cinquè valor sigui 1


In [15]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## **Exercici 4**

Crea una matriu 3x3 amb valors de 0 a 8

In [16]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## **Exercici 5**

Normalitza una matriu random 5x5

La normalizació (feature scaling) consisteix en estandaritzar un conjunt de variables independents. 
És molt comú en el processat de dades. El mètode més senzill consisteix en reescalar les variables entre 0.0 i 1.0 seguint la fórmula seguent:


$$x'={\frac  {x-{\text{min}}(x)}{{\text{max}}(x)-{\text{min}}(x)}}$$

In [17]:
np.random.seed(0)
x = np.random.random((5,5)) * 30 
print(x)

print("\nNormalització de la matriu anterior amb valors entre 0 - 1:\n")
(x - x.min()) / (x.max() - x.min())



[[16.46440512 21.45568099 18.08290128 16.34649549 12.70964398]
 [19.37682339 13.12761634 26.75319002 28.90988282 11.50324556]
 [23.75175114 15.86684759 17.04133683 27.76789915  2.13108175]
 [ 2.61387899  0.60655192 24.97859537 23.34470253 26.10036445]
 [29.35855027 23.97475693 13.84438087 23.41587529  3.54823278]]

Normalització de la matriu anterior amb valors entre 0 - 1:



array([[0.55153917, 0.7251367 , 0.60783077, 0.54743825, 0.42094786],
       [0.65283363, 0.43548501, 0.90938507, 0.98439526, 0.37898909],
       [0.80499445, 0.530756  , 0.57160496, 0.94467685, 0.05302344],
       [0.06981522, 0.        , 0.84766433, 0.79083723, 0.88667967],
       [1.        , 0.81275064, 0.46041422, 0.79331263, 0.10231222]])

## **Exercici 6**

Crea un array 10x10  amb uns a tots els marges i zeros a l'interior
<table>
  <tr>
    <td>1</td>
    <td>1</td> 
    <td>1</td>
    <td>1</td>
  </tr>
  <tr>
    <td>1</td>
    <td>0</td> 
    <td>0</td>
    <td>1</td>
  </tr>
    <tr>
    <td>1</td>
    <td>0</td> 
    <td>0</td>
    <td>1</td>
  </tr>
    <tr>
    <td>1</td>
    <td>1</td> 
    <td>1</td>
    <td>1</td>
  </tr>
  
</table>

In [18]:
#Alternativa 1
x = np.zeros((10, 10))

x[0,:] = 1
x[-1,:] = 1
x[:,0] = 1
x[:,-1] = 1

x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
#Alternativa 2
a = np.ones((10,10))
a[1:9] = 0
a[:,0] = 1
a[:,9] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
#Alternativa 3
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## **Exercici 7**

Crea un array 10x10  amb un patró de tauler d'escacs.
<table>
  <tr>
    <td>1</td>
    <td>0</td> 
    <td>1</td>
    <td>0</td>
  </tr>
  <tr>
    <td>0</td>
    <td>1</td> 
    <td>0</td>
    <td>1</td>
  </tr>
    <tr>
    <td>1</td>
    <td>0</td> 
    <td>1</td>
    <td>0</td>
  </tr>
    <tr>
    <td>0</td>
    <td>1</td> 
    <td>0</td>
    <td>1</td>
  </tr>
  
</table>

In [21]:
#Opció començant per una taula de 0s
x = np.zeros((10,10))
x[::2, ::2] = 1
x[1::2, 1::2] = 1
x

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [22]:
#Opció començant per una taula de 1s
x = np.ones((10,10))
x[::2, 1::2] = 0
x[1::2, ::2] = 0
x

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

## **Exercici 8**

Donat una array Z d'una dimensió, canvia el signe dels elements entre els valors 3 i 8

In [23]:
Z = np.arange(11)

Z[3:8] = Z[3:8]*(-1)
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9, 10])

## **Exercici 9**

Crea un vector random de tamany 10 i canvia el seu valor màxim per zero

In [24]:
#Alternativa 1
np.random.seed(10)
x = np.random.randint(low=0, high=100, size=10)
print(x)

x[x.argmax()] = 0
print(x)

[ 9 15 64 28 89 93 29  8 73  0]
[ 9 15 64 28 89  0 29  8 73  0]


In [25]:
#Alternativa 2
np.random.seed(10)
x = np.random.randint(low=0, high=100, size=10)
display(x)

x.max()
x[x == 93] = 0
x

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

array([ 9, 15, 64, 28, 89,  0, 29,  8, 73,  0])

## **Exercici 10**

Troba quin és el valor més proper dins un array (Z) a un valor donat (z). Pista: fes-ho a partir de la difència de Z amb el valor z.

In [26]:
np.random.seed(0)
Z = np.random.uniform(0,1,10)
z = 0.5

display(Z, z)

x = Z-z
display("DIFERÈNCIA AMB z:", x)

x = np.abs(x)
display("VALOR ABSOLUT DE LA DIFERÈNCIA:", x)

imin = x.argmin()
display("INDEX AMB LA DIFERÈNICA MÍNIMA:", imin)

xmin = Z[imin]
display("VALOR AMB LA DIFERÈNICA MÍNIMA:", xmin)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

0.5

'DIFERÈNCIA AMB z:'

array([ 0.0488135 ,  0.21518937,  0.10276338,  0.04488318, -0.0763452 ,
        0.14589411, -0.06241279,  0.391773  ,  0.46366276, -0.11655848])

'VALOR ABSOLUT DE LA DIFERÈNCIA:'

array([0.0488135 , 0.21518937, 0.10276338, 0.04488318, 0.0763452 ,
       0.14589411, 0.06241279, 0.391773  , 0.46366276, 0.11655848])

'INDEX AMB LA DIFERÈNICA MÍNIMA:'

3

'VALOR AMB LA DIFERÈNICA MÍNIMA:'

0.5448831829968969

In [27]:
# El mateix en una sola linea:
Z[np.abs(Z - z).argmin()]

0.5448831829968969

## **Exercici 11**

Substitueix tots els nombres parells d'un array per -1

In [28]:
X = np.arange(20)
display(X)

index = X % 2 == 0
display(index)

X[index] = -1
display(X)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15, -1,
       17, -1, 19])

## **Exercici 12**

Troba les posicions (índex) on els array a i b coincideixin. 

In [29]:
x = np.array([1,2,3,2,3,4,3,4,5,6])
y = np.array([7,2,10,2,7,4,9,4,9,8])

xy, = np.where(x==y)

display(xy)

array([1, 3, 5, 7])